# Virtual repos list member repo keys as strings, so Terraform does not infer
# create-order against local/remote resources. This gate waits for them first.

resource "terraform_data" "local_and_remote_ready" {
  depends_on = [
    artifactory_local_docker_v2_repository.this,
    artifactory_local_maven_repository.this,
    artifactory_local_gradle_repository.this,
    artifactory_local_npm_repository.this,
    artifactory_local_pypi_repository.this,
    artifactory_local_helm_repository.this,
    artifactory_local_generic_repository.this,
    artifactory_local_go_repository.this,
    artifactory_local_debian_repository.this,
    artifactory_local_rpm_repository.this,
    artifactory_local_nuget_repository.this,
    artifactory_local_conan_repository.this,
    artifactory_local_cargo_repository.this,
    artifactory_local_gems_repository.this,
    artifactory_local_composer_repository.this,
    artifactory_local_terraform_module_repository.this,
    artifactory_local_terraform_provider_repository.this,
    artifactory_local_oci_repository.this,
    artifactory_local_alpine_repository.this,
    artifactory_local_ansible_repository.this,
    artifactory_local_nix_repository.this,
    artifactory_remote_docker_repository.this,
    artifactory_remote_maven_repository.this,
    artifactory_remote_gradle_repository.this,
    artifactory_remote_npm_repository.this,
    artifactory_remote_pypi_repository.this,
    artifactory_remote_helm_repository.this,
    artifactory_remote_nuget_repository.this,
    artifactory_remote_generic_repository.this,
    artifactory_remote_go_repository.this,
    artifactory_remote_debian_repository.this,
    artifactory_remote_rpm_repository.this,
    artifactory_remote_conan_repository.this,
    artifactory_remote_cargo_repository.this,
    artifactory_remote_gems_repository.this,
    artifactory_remote_composer_repository.this,
    artifactory_remote_terraform_repository.this,
    artifactory_remote_oci_repository.this,
    artifactory_remote_vcs_repository.this,
    artifactory_remote_alpine_repository.this,
    artifactory_remote_ansible_repository.this,
  ]
}
